package example.cucumber;

import io.cucumber.java.en.And;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class StepNavegacion {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Given("Abro el navegador en la pagina web principal")
    public void abroElNavegadorEnLaPaginaWebPrincipal() {
        //System.setProperty("webdriver.chrome.driver", "C:\\Users\\pepesan\\Downloads\\chromedriver_win32\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        // Test name: Cursos
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://cursosdedesarrollo.com/");
    }

    @When("Voy a la pagina de profesores mediante el menu")
    public void voyALaPaginaDeProfesoresMedianteElMenu() {
        // 2 | click | css=.g-menu-item-2313 .g-menu-item-title |
        driver.findElement(By.cssSelector(".g-menu-item-2313 .g-menu-item-title")).click();
    }

    @Then("Deberia aparecer el con el titulo magento")
    public void deberiaAparecerElConElTituloMagento() {
        // 3 | assertElementPresent | linkText=Magento |
        {
            List<WebElement> elements = driver.findElements(By.linkText("Magento"));
            assert(elements.size() > 0);
        }
    }

    @And("Cierro el navegador")
    public void cierroElNavegador() {
        driver.quit();
    }


    @When("Voy a la pagina de usera")
    public void voyALaPaginaDeUsera() {
        driver.get("https://decide.madrid.es/presupuestos");
        // driver.findElement(By.id("iam-cookie-control-modal-action-primary")).click();
        // driver.findElement(By.cssSelector("a [href]='/budgets/presupuestos-participativos-2021/investments/18956'")).click();
    }

    @When("hago click en la primera propuesta")
    public void hagoClickEnLaPrimeraPropuesta() {
        driver.findElement(By.linkText("Paso peatonal a la entrada trasera del colegio Edith Stein")).click();
        driver.findElement(By.cssSelector("h1:nth-child(1)")).click();
    }

    @Then("Compruebo los titulos")
    public void comprueboLosTitulos() {
        assertThat(driver.getTitle(), is("Paso peatonal a la entrada trasera del colegio Edith Stein"));
        assertThat(driver.findElement(By.cssSelector("#investment_code > strong")).getText(), is("17045"));
    }
}
