package example.selenium;
// Generated by Selenium IDE
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CursosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    //System.setProperty("webdriver.chrome.driver", "C:\\Users\\pepesan\\Downloads\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Tag("aceptacion")
  public void cursos() throws InterruptedException {
    // Test name: Cursos
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://cursosdedesarrollo.com/");
    // 2 | click | css=.g-menu-item-2313 .g-menu-item-title | 
    driver.findElement(By.cssSelector(".g-menu-item-2313 .g-menu-item-title")).click();
    // 3 | assertElementPresent | linkText=Magento | 
    {
      List<WebElement> elements = driver.findElements(By.linkText("Magento"));
      assert(elements.size() > 0);
    }
  }
}
